# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^docs/source/generated/
    -   id: end-of-file-fixer
        exclude: ^docs/source/generated/
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: no-commit-to-branch
        args: ['--branch', 'main']
-   repo: https://github.com/pycqa/flake8
    rev: '5.0.4'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
# - repo:  https://github.com/milin/giticket
#   rev: v1.3
#   hooks:
#   - id:  giticket
#     args: ['--regex=PROJ-[0-9]', '--format={ticket} {commit_msg}']  # Optional
